### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by vadistic** [vadistic/graphql-extra#8]
# Roadmap

This is umbrella issse for further development ideas.

There's already quite a bit of hidden functionality here that could be better exposed, also there are low-hanging fruits that could be baked in.

### New
- [ ] Operations support https://github.com/vadistic/graphql-extra/issues/1
- [ ] Add high-level/standalone common typedefs transformations (sorting/ generate fragments/ merge extensions etc.)
- [ ] Come up with fast, lightweight & clean data structure for GraphQL schema  that would be usable for various client-side impementations and could replace all those array loops internally
- [ ] jest-matchers. Is there a use-case for set of graphql jest matchers (something like `react-testing-library`/`enzyme` but for sdl?

### Improvement
- [ ] Investigate if all those api crud method aliases improve DX or just bloat codebase
- [ ] Normalise methods naming - get vs find ? :)
- [ ] Expose more powerful searches-by-partials that are currently hidden behind _underscore
- [ ] Improve typeApi - currently it's quite limited - also comparing type shapes does not work as expected

### Promotion
- [ ] Documentation https://github.com/vadistic/graphql-extra/issues/5
- [ ] Examples https://github.com/vadistic/graphql-extra/issues/7
- [ ] Show the world

### Build
- [ ] Split `ast` module into separate package - it's a core for all functionallity, but with all apis this lib is 300kb which makes it quite unsuitable for client-side

### Testing
- [ ] finish unit-testing of document apis
